services:
    antispam:
        build: "antispam"
        ports:
            - "5000:5000"
    emaildb:
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=emaildb_client
            - MONGO_INITDB_ROOT_PASSWORD=hiddenpassword
    userdb:
        image: mongo:latest
        ports:
            - "27117:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=userdb_client
            - MONGO_INITDB_ROOT_PASSWORD=hiddenpassword
