# Generated by Django 3.2.2 on 2021-05-18 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('receiver', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(null=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('attachment', models.URLField(blank=True)),
            ],
        ),
    ]
