# Generated by Django 3.2.3 on 2021-07-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_email_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='time',
            field=models.TimeField(default='19:23:42'),
        ),
    ]
