# Generated by Django 3.2.3 on 2021-07-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_email_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='isSpam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='time',
            field=models.TimeField(default='13:42:41'),
        ),
    ]
