# Generated by Django 3.2.3 on 2021-07-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_auto_20210713_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='time',
            field=models.TimeField(default='21:02:28'),
        ),
    ]
