# Generated by Django 3.2.3 on 2021-05-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
