# Generated by Django 3.2.3 on 2021-05-25 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
