# Generated by Django 3.2.3 on 2021-05-29 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
