# Generated by Django 3.2.3 on 2021-07-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
