apiVersion: apps/v1
kind: Deployment
metadata:
  name: antispam
  labels:
    app: antispam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: antispam
  template:
    metadata:
      labels:
        app: antispam
    spec:
      containers:
        - name: antispam
          image: emailservice/antispam:0.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: antispam
spec:
  selector:
    app: antispam
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000