### Get accounts

GET http://127.0.0.1:8000/accounts/ HTTP/1.1\r\n
Content-Type: application/json

### Get account with specific id

GET http://127.0.0.1:8000/accounts/32 HTTP/1.1\r\n
Content-Type: application/json


### Registration

POST http://127.0.0.1:8000/auth/signup/ HTTP/1.1\r\n
Content-Type: application/json

{
    "first_name": "Nikos",
    "last_name": "Papadopoulos",
    "email": "email",
    "date_of_birth": "2000-12-12",
    "password": "F31l0f0s@",
    "confirm": "F31l0f0s@"
}

### Login

POST http://127.0.0.1:8000/auth/login/ HTTP/1.1\r\n
Content-Type: application/json

{
    "email": "email",
    "password": "F31l0f0s@"
}

### Logout

POST http://127.0.0.1:8000/auth/logout/ HTTP/1.1\r\n
Content-Type: application/json

### Delete account with specific id

DELETE http://127.0.0.1:8000/accounts/delete/33 HTTP/1.1\r\n
Content-Type: application/json

### Update account data

PATCH http://127.0.0.1:8000/profile/ HTTP/1.1\r\n
Content-Type: application/json

{
    "password": "F331l0f0s@",
    "confirm": "F331l0f0s@"
}
