# Generated by Django 3.2.3 on 2021-06-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='attachment',
        ),
        migrations.AddField(
            model_name='email',
            name='response',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='time',
            field=models.TimeField(default='19:48:00'),
        ),
    ]
