# Generated by Django 3.2.3 on 2021-07-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20210627_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='time',
            field=models.TimeField(default='09:53:14'),
        ),
    ]
